//==UserScript==
//@name        OSU! Tweaks
//@namespace   AdventShit
//@version     2.1
//@description Auto-Import, Auto-Close, Auto-NSFW, and additional componets for my theme. Poggers.
//@author      Advent
//@match       *://osu.ppy.sh/*
//@grant       none
//@downloadURL https://github.com/AdventGit/Userscripts-Things/raw/main/OSU!%20Tweaks.user.js
//==/UserScript==
const playableRatio=0.88;
const waitLen=100;
function osuStyles(){const styles=':root{--tint:rgb(51,181,229);--card-color:#262626;}body.osu-layout div.profile-detail-bar__level{background-image:none!important;}';$('head').append('<style type="text/css">'+styles+'</style>');}
function buttonSet(ele,ctx,subfix){if($(ele+subfix,ctx).length!==0){return($(ele+subfix,ctx))}else{if($(ele+'data-orig-'+subfix,ctx).length!==0){return($(ele+'data-orig-'+subfix,ctx))}else{return('Fixed')}}}
function buttonEdit(ele,clickCTX,href,addCSS){if(typeof ele!==undefined){if(ele!=='Fixed'){ele.off('click');ele.prop('disabled',false);ele.on('click.'+clickCTX,()=>{window.location.href=href});if(addCSS){ele.css('cursor','pointer')}ele.addClass('fixed');}return(true);}else{return(false)}}
function osuFixButtons(){const baseTarget=$('body>div.user_show>div.osu-layout>div>div.osu-layout>div[data-page-id="main"]>div.osu-page>div.profile-header');const friendButton=buttonSet('>div[',$('>div.profile-detail>div.profile-detail__bar>div.profile-detail-bar>div.profile-detail-bar__column--left>div.profile-detail-bar__entry:nth-of-type(1)',baseTarget),'title="followers"]>button.user-action-button:not(.fixed)');const supportButton=buttonSet('>span[',$('>div.profile-header__top>div.profile-info>div.profile-info__details>div.profile-info__icon-group>div.profile-info__icons:not(.profile-info__icons--flag)',baseTarget),'title="osu!supporter"]:not(.fixed)');if(buttonEdit(friendButton,'friendButton','https://osu.ppy.sh/home/friends',false)&buttonEdit(supportButton,'supportButton','https://osu.ppy.sh/home/support',true)){setTimeout(()=>{osuFixButtons()},500)}}
function osuLevelSVG(){const levelSVGParent=$('div.profile-detail-bar__entry.profile-detail-bar__entry--level');const customLevelSVG='<svg id="custom-level" data-name="custom-level" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 86.6 100" style="position: absolute !important;height: calc(100%+10px) !important;width: 50px !important;"><title>custom-level</title><path class="custom-level_cls-1" style="fill: var(--tint) !important;"d="M43.3,8.45A17.3,17.3,0,0,1,52,10.77L73,22.89a17.35,17.35,0,0,1,8.64,15V62.13a17.35,17.35,0,0,1-8.64,15L52,89.23a17.29,17.29,0,0,1-17.3,0l-21-12.12A17.34,17.34,0,0,1,5,62.13V37.87a17.34,17.34,0,0,1,8.65-15l21-12.12A17.3,17.3,0,0,1,43.3,8.45m0-5a22.2,22.2,0,0,0-11.15,3l-21,12.12A22.31,22.31,0,0,0,0,37.87V62.13A22.31,22.31,0,0,0,11.15,81.44l21,12.12a22.28,22.28,0,0,0,22.3,0l21-12.12A22.32,22.32,0,0,0,86.6,62.13V37.87A22.32,22.32,0,0,0,75.46,18.56l-21-12.12a22.2,22.2,0,0,0-11.15-3Z"/></svg>';if(levelSVGParent.length!==0){levelSVGParent.append(customLevelSVG)}else{setTimeout(()=>{osuLevelSVG()},waitLen)}}
function osuDirectClicker(){const beatmapCircleCount=$('div.beatmap-basic-stats__entry[title="Circle Count"]>span');if(beatmapCircleCount.length!==0){const circleCount=Number(beatmapCircleCount.text().replace(',',''));const sliderCount=Number($('div.beatmap-basic-stats__entry[title="Slider Count"]>span').text().replace(',',''));const beatmapRatio=((100/circleCount)*sliderCount)/100;if(circleCount<=sliderCount||playableRatio<=beatmapRatio){window.close()}else{const osuDirectButton=$('div.beatmapset-header__buttons>a:nth-of-type(2)>span>span>span');if(osuDirectButton.length!==0){if(osuDirectButton.text()=='osu!direct'){window.location.href=$('div.beatmapset-header__buttons>a:nth-of-type(2)')[0].href}else{window.location.href=$('div.beatmapset-header__buttons>a:nth-of-type(3)')[0].href};setTimeout(()=>{window.close()},15);}else{setTimeout(()=>{osuDirectClicker()},waitLen)}}}else{setTimeout(()=>{osuDirectClicker()},waitLen)}}
function osuNotFound(){if($('body').hasClass('action-404')){window.close()}}
function osuExplicitAuto(){const nsfwDiv='div.osu-page>div.nsfw-warning';if($('div.osu-page>div.header-v4 header-v4--beatmapsets').length!==0){return(true)}else if($(nsfwDiv).length!==0){const nsfwDisableButton=$(nsfwDiv+'>div.nsfw-warning__row--buttons>button.nsfw-warning__button--show:nth-of-type(1)');if(nsfwDisableButton.length!==0){nsfwDisableButton.click()}else{setTimeout(()=>{osuExplicitAuto()},waitLen)}}else{setTimeout(()=>{osuExplicitAuto()},waitLen)}}
function toDo(){osuStyles();osuNotFound();osuExplicitAuto();osuDirectClicker();osuFixButtons();osuLevelSVG();}
(()=>{'use strict';toDo();})();